### ISSUE TITLE
UI issue minting a new character

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#10]
When minting a new character the new popup noting spawning a character. This is overlapping with the TV style frame on the site. 

Error -
<img width="517" alt="Screenshot 2023-05-05 at 16 37 19" src="https://user-images.githubusercontent.com/114863662/236506604-844ce07b-901e-4374-9c12-76eeb4c3f083.png">

**Comment by starknetdev** [comment]
Can you check if the error still persists? We have increased the boxes margins
