### ISSUE TITLE
Upgrade screen cannot see your adventurer (UI)

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#101]
When you level up and are locked into the upgrade screen, the is no easy access to your characters details. You can go back to character selection screen to review but doesn't make a smooth gameplay experience.

- [ ] It would be nice to be able to see your whole adventure and think about your choice fully including both your skills and your items/health.

<img width="708" alt="Screenshot 2023-06-01 at 17 41 37" src="https://github.com/BibliothecaDAO/loot-survivor/assets/114863662/734c0d22-f822-4eb2-b0d4-0289032b5ee3">

**Comment by spaghettiOnToast** [comment]
Add info screen to page
