### ISSUE TITLE
Can we use a decay function to the marketplace? Possibly even reset the entire marketplace on market refresh (bar the current items with bids)

### ISSUE THREAD

**Issue by loothero** [BibliothecaDAO/loot-survivor#104]

**Comment by Calcutatator** [comment]
gm

### Summary
Marketplace requires churn. With normal auction houses within mmo games and the real world the is always a churn of items within it. Auctions last a set amount of time, can be hours weeks days. People take items down when prices alter. We need to have a way to simulate that feeling that what is live is not going to be there when you come back, you should work with what is there.

The prior build meta fell into waiting, wait for tier 1's to be available - wait for what you want and it will probably show. We need a feeling of urgency to get an item.

This game aims to have low amount of play time within hours per run. Hence I think that churn of auction items should be quite high.

### Possible Fixes
(I have no idea feasibility or complexity to implement but going to throw down a few ideas to increase churn in the marketplace)
- When an item is auctioned it is set a expiration time. Could be random for each item or a set time for all items.
- Items randomly expire. Each block an item has a small chance to delist.
- Imaginary bids on items. Small chance a random item is bid on by a non player.
- Randomly set minimum bids per item. The tiers have a range of minimum price not a set minimum. (This doesn't increase churn as such but would make the marketplace feel more alive)

It is possible the more recent updates may solve for most of this urgency so this all might be redundant but could be useful further down the line to make the marketplace feel more alive.

**Comment by Calcutatator** [comment]
Didn't want to waffle on but I think the ideas come to making the listings feel more realistic as these are not set by players we have to make them feel more like they are. 

In turn making the player more immersed and adding more urgency to the marketplace.

**Comment by starknetdev** [comment]
Similar to #66 this is now obsolete due to marketplace changes.
