### ISSUE TITLE
Hide option for Characters

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#11]
Request to have a way to remove or hide characters. Currently if you duplicate characters or have many you cannot filter easily. Being able to remove some would make organising a lot easier, especially for dupes.

Possible button to "sacrifice character" deleting them, or more simply "hide" or "delete" buttons.

<img width="1233" alt="Screenshot 2023-05-05 at 17 13 10" src="https://user-images.githubusercontent.com/114863662/236511509-d2f14bcd-02ac-4ed4-826d-c3ec46a7d010.png">

**Comment by spaghettiOnToast** [comment]
Had a look into this, we can put something in but every time there is a refresh they will appear again unless we have a database, which isn't something we can do right now but it is definitely possible for v2.

**Comment by Calcutatator** [comment]
Would it be possible to maybe get a sort function on it then? So we could quickly filter to our higher level characters or maybe our alive ones..

**Comment by starknetdev** [comment]
We will sort it by highest level as default and include a "Hide Dead"

**Comment by LordSquiddy** [comment]
Hide Dead would be good - would it be possible to put a skull perhaps next to the ones that have died?
