### ISSUE TITLE
Marketplace bidding incorrectly calculating charisma effect (UI)

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#111]
The new patch is noted to reduce cost by 3 per charisma point. I believe it is still set to 1 reduction in the UI.

Example :
<img width="1554" alt="Screenshot 2023-06-03 at 22 52 41" src="https://github.com/BibliothecaDAO/loot-survivor/assets/114863662/ac6570d1-b4c2-4df4-8d9c-4bab802cd331">
The above is a character with 1 Charisma (3 reduction of cost) attempting to bid on a tier 1 item. The minimum bid should be 12 but the current UI does not allow you to bid under 14.

**Comment by starknetdev** [comment]
Should be fixed, please let me know if any more issues
