### ISSUE TITLE
Maximum update depth exceeded error

### ISSUE THREAD

**Issue by 0rli-E** [BibliothecaDAO/loot-survivor#117]
![image](https://github.com/BibliothecaDAO/loot-survivor/assets/39305954/18823f96-461d-4b45-b953-be8980b6b5ed)

Got this error while heading into the mist. Got the same error before that when fighting an ogre and couldnt attack but had to flee. This started once i had created a second adventurer and played with it. 

States "Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops."

Oh and environment mac book air, apple silicon and using chrome + braavos wallet

**Comment by 0rli-E** [comment]
Oh and environment mac book air, apple silicon and using chrome + braavos wallet

**Comment by starknetdev** [comment]
Have seen what now causes this error and recent upgrades should have made it obsolete.
