### ISSUE TITLE
Embrace duel wielding characters (UI)

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#118]
gm

Most highly active players are using multiple screens or squeezing two tabs into one pane. It might be a good idea to embrace this style of play until the block times are drastically reduced.
<img width="1680" alt="Screenshot 2023-06-04 at 17 53 59" src="https://github.com/BibliothecaDAO/loot-survivor/assets/114863662/5cc51937-002f-44fe-af60-17574f6464e6">

Would it be possible to add a tab section near the top of the main page allowing you to segment out different adventurers and quickly switch out runs? This would for sure make the whole experience a lot more engaging.

**Comment by Calcutatator** [comment]
Thinking about it maybe a way to remove the waiting block when switching characters would actually do the exact same thing 

<img width="442" alt="Screenshot 2023-06-04 at 18 09 09" src="https://github.com/BibliothecaDAO/loot-survivor/assets/114863662/1ac4168e-a10d-4608-9aa8-9c45e2a9176b">

**Comment by starknetdev** [comment]
Currently the loading state is attached to adventurer, so It should be possible to switch adventurer while another TX is ongoing.

Are you able to try this?
