### ISSUE TITLE
UX - can claim and equip be bundled?

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/loot-survivor#123]
from claim to equipped in one button

**Comment by LordSecretive** [comment]
from Loothero

Yeah, frontned could do a multicall I believe or we could include logic in the contract to auto equip if you claim an item for a slot with nothing equipped yet

**Comment by starknetdev** [comment]
It's not as easy as a simple multicall unfortunatley. But we might be able to hack a way to do this. Will investigate!
