### ISSUE TITLE
UX - behaviour of leaderboard page buttons + search

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/loot-survivor#127]
The back and forward buttons move reactively as you click, meaning you have to keep moving the mouse to follow the button.  Leads to misclicks and frustration when searching for a player

A search function is an alternative fix, but both preferable

![image](https://github.com/BibliothecaDAO/loot-survivor/assets/102318873/dcac7bb3-5758-4077-badb-bb1a7b433b99)

**Comment by starknetdev** [comment]
Made a quick fix that now shows first and last pages as selectable but otherwise just back and next.
