### ISSUE TITLE
Beast battle text description not updating

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#14]
When entering a new battle with a new beast the text does not consistently remove the text description. 

Example below. This is a new battle and I am yet to attack the Orc that has just been found.  Text is showing the prior battle I had with a Wraith but replaced all the text to new found beast.
<img width="1484" alt="Screenshot 2023-05-05 at 19 56 19" src="https://user-images.githubusercontent.com/114863662/236545204-5caee425-e11d-400d-9d4e-eba253776479.png">

**Comment by starknetdev** [comment]
Handled in our data manager update
