### ISSUE TITLE
Parallel Character runs clashing 

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#28]
### Summary
When running multiple characters the UI will block you from being able to execute a transaction on a separate character until the current character action is complete.

### Example 

1. Character 1 is in battle.
2. Character 2 is not in battle.
3. Character 1 sends a trx to attack beast.
4. Character 2 attempts to submit an "Into the mist" transaction but is blocked due to Character 1 transaction has not been settled. 

This causes you to wait till Character 1 transaction has settled, multiplying your waiting for transactions.

### Fix

- [x] Allow for different instances within the UI. Not to block transactions on separate characters.

**Comment by starknetdev** [comment]
Fixed by #36
