### ISSUE TITLE
Says AA is 'Account Already Stored' but I can't see it in my Arcade Accounts - screenshots below

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/loot-survivor#456]
![image](https://github.com/BibliothecaDAO/loot-survivor/assets/102318873/8d335a02-d2fd-4774-bb36-97bfd95d90a4)

![image](https://github.com/BibliothecaDAO/loot-survivor/assets/102318873/d6ebaa8c-5649-4c65-b650-88396d993840)

**Comment by starknetdev** [comment]
Removing the filter we have to only display arcade accounts for the current contract. Will detect if the current contract is the is the one stored. If not, highlight they need to set permissions and update it.

**Comment by starknetdev** [comment]
We removed the filter as there were issues with players who had previously played on testnet at this url
