### ISSUE TITLE
Is it possible to put into the client an estimate of their wait time to start, based upon current block time?

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/loot-survivor#457]
Is it possible to put into the client an estimate of their wait time to start, based upon current block time?

Atm the player won't know if it is 7 mins or 33 mins until after the Lords have gone in

loaf — Today at 20:23
yeah perhaps a warning on creating the AA
or maybe just before they start the gaem
and actually spend

**Comment by starknetdev** [comment]
Closed by the above PR
