### ISSUE TITLE
Suggest changing wording of 404 screen - misleading, think that game is over

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/loot-survivor#464]
![image](https://github.com/BibliothecaDAO/loot-survivor/assets/102318873/6f2f3713-af91-42f6-991d-e67b56c7eb72)

**Comment by LordSecretive** [comment]
Your adventurer has been stalled by an unexpected bug! Refresh now, hit the connect button, then go back to start and find your character

**Comment by starknetdev** [comment]
This has been changes
