### ISSUE TITLE
Game not playable on Argent mobile 

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/loot-survivor#522]
<img width="516" alt="image" src="https://github.com/BibliothecaDAO/loot-survivor/assets/102318873/0492cc14-3302-4c61-b3f5-c52f9a17ffce">
<img width="516" alt="image" src="https://github.com/BibliothecaDAO/loot-survivor/assets/102318873/31970e51-61e1-44b9-acbc-687a9f2f6f4e">

**Comment by starknetdev** [comment]
Closed with #527
