### ISSUE TITLE
Adding PFP and Starknames using useStarkProfile

### ISSUE THREAD

**Issue by sdaav** [BibliothecaDAO/loot-survivor#573]
### Description 

Hello!

It would be super cool to make the Starknet.id integration by adding PFPs using our documentation.

Based on each repo we will adapt the method used (check all methods https://docs.starknet.id/)

You have several choices: 

- Starknetid.js
- Starknet React
- Starknet.js
- API 

Up to you to choose the best method for each repository, the best will be to use the library you are already using! 

@Marchand-Nicolas, one of our team members, can help to do it if needed!

### Proposed to do

- [ ] .STARK name & PFP displayed after connecting the wallet

Why not replace the GitHub logo by the PFP!

<img width="206" alt="Capture d’écran 2024-03-25 à 17 21 10" src="https://github.com/BibliothecaDAO/loot-survivor/assets/57441909/6b49eaad-c1e2-4ede-9e2d-d515ab61fd80">

- [ ] .STARK name & PFP displayed on this space

<img width="326" alt="Capture d’écran 2024-03-25 à 17 20 39" src="https://github.com/BibliothecaDAO/loot-survivor/assets/57441909/92b85405-f5de-4f6c-95cb-3fb6457dc246">

- [ ] Create subdomain for your leaderboard

If you want to create a subdomain, don't hesitate to reach out.

<img width="588" alt="Capture d’écran 2024-03-25 à 17 29 25" src="https://github.com/BibliothecaDAO/loot-survivor/assets/57441909/adae8318-0fbc-4a0d-b239-7b01ce557827">

**Comment by EjembiEmmanuel** [comment]
@sdaav please I would like to work on this

**Comment by sdaav** [comment]
@EjembiEmmanuel hey, this issue is not open for contribution 🙏
