### ISSUE TITLE
UI consistency with beast/characters

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#65]
Should the Level of your character be highlighted yellow to match the beast level?

<img width="1492" alt="Screenshot 2023-05-26 at 18 29 11" src="https://github.com/BibliothecaDAO/loot-survivor/assets/114863662/0d1028f7-41fb-4538-a545-fa3fd41e0fa0">

**Comment by starknetdev** [comment]
We will take it into account and see if anyone else thinks the same, it's a very easy fix
