### ISSUE TITLE
Reduce marketplace refreshes significantly

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#66]
Playing Today with up to ten players and the marketplace refresh time is too long and is disrupting the flow of the game.

Propose 30 minute refreshes with 10 minute bid times or something close this.

**Comment by Calcutatator** [comment]
Note also speaking about changing the time limit to transaction count based not time based

**Comment by starknetdev** [comment]
I am marking this as obsolete since marketplace has changed to adventurer based (not shared)
