### ISSUE TITLE
I cannot see characters I'm approved to control on my "Start" screen

### ISSUE THREAD

**Issue by zomglings** [BibliothecaDAO/loot-survivor#71]
https://github.com/wighawag approved me to control his character (`tokenId: 67`): https://testnet.starkscan.co/tx/0x1d9005dc3896a53a64bef2bbb8f40e0f32c98c9ce7f3bf93f1220f99ffb3400

But I don't see the character on my `Start` screen:

![image](https://github.com/BibliothecaDAO/loot-survivor/assets/8016073/f32ec77b-6cc5-4d06-bc08-f455419165b8)

**Comment by starknetdev** [comment]
There isn't a way to share adventurers as they are (should be) SBTs. We should remove the contract functions for approve and transfer.

**Comment by starknetdev** [comment]
Functions have been removed, you should not be able to transfer adventurers
