### ISSUE TITLE
After I experienced a "fee transfer failure" on explore, the frontend crashed when I tried to explore again

### ISSUE THREAD

**Issue by zomglings** [BibliothecaDAO/loot-survivor#73]
Despite the client's advice, I did *not* refresh.

The failed exploration: https://testnet.starkscan.co/tx/0x168a1604ab29044764419bc26080035c8fef0d08f8be2b4c1bdf7ad293766d7

Successful exploration submitted: https://testnet.starkscan.co/tx/0x018c97601968c8ad699c6903c60f456a818105dcb1763bfd35623bc319ce1ffc

Client error: 
![image](https://github.com/BibliothecaDAO/loot-survivor/assets/8016073/589c3822-75e7-469f-95bb-58feff59ef99)

**Comment by starknetdev** [comment]
Fee transfer failures should have been reduced based on various starknet upgrades and improvements (most notably 0.12 coming imminently)
