### ISSUE TITLE
Actions, Market, Inventory, etc. grayed out

### ISSUE THREAD

**Issue by zomglings** [BibliothecaDAO/loot-survivor#74]
This is not a bug, but it is an opinion that may be useful to you.

It is jarring to see important tabs grayed out on the game client:
![image](https://github.com/BibliothecaDAO/loot-survivor/assets/8016073/e22bc38f-fb13-4e12-8b91-4384da340b01)

It would be better if I could click on those screens but not interact with them if the character is doing something else at that time.

**Comment by starknetdev** [comment]
Partly solved in #107 for Market & Inventory (these are tasks that can be carried out when upgrading)

Still thinking on Actions
