### ISSUE TITLE
fix: zero out dead adventurers gold balances

### ISSUE THREAD

**Issue by ponderingdemocritus** [BibliothecaDAO/loot-survivor#75]
Dead adventurers gold balances should be cleared, otherwise the market includes this balance when calculating how many items to create

**Comment by starknetdev** [comment]
@loothero I thought we added this but I can't actually see it in the code, do you know if/where it is?

**Comment by loothero** [comment]
Closing this as a duplicate of https://github.com/BibliothecaDAO/realms-contracts/issues/355 which I'll have fixed shortly
