### ISSUE TITLE
'Choose Adventurer' button sometimes doesn't/takes a long time to load

### ISSUE THREAD

**Issue by LordSquiddy** [BibliothecaDAO/loot-survivor#76]
Sometimes the 'Choose Adventurer' button doesn't appear, but it could be just due to the slow network? 

It happened to me so I created a new adventurer, and then the original was there once the new one appeared. 

This is happening to a few other players and they said you have to leave it pending for a while, and then refresh to resolve.

(please ignore if this is out of our control)

**Comment by loothero** [comment]
@LordSquiddy this was almost certainly due to our server being overwhelmed. We made some optimizations and upgraded our server infrastructure to a system with 10-20x more compute power

I'm going to optimistically close this issue, feel free to reopen though if you see it moving foward
