### ISSUE TITLE
Time based health decay when you are below X HP

### ISSUE THREAD

**Issue by GrugLikesRocks** [BibliothecaDAO/loot-survivor#82]
That will push people to keep on playing and getting killed (or survive)

**Comment by loothero** [comment]
🔥 suggestions Grug!

What do you think about https://github.com/BibliothecaDAO/realms-contracts/issues/351?

I think a health decay would be ideal but it's a lot more complex to implement

**Comment by starknetdev** [comment]
A 'slay adventurer' function has been implemented in the upcoming cairo 1 version, namely #163
