### ISSUE TITLE
Queries overloading server

### ISSUE THREAD

**Issue by starknetdev** [BibliothecaDAO/loot-survivor#95]
Current issue is current player base is driving high CPU usage of the server. I have assumed for now this is due to the number of queries the users send, these can be largely optimised/reduced.

Some ideas to implement and improve the query model, each need more testing:

- Only send TX related queries when TX is accepted and a hash exists
- Have a market refresh button instead of querying every 5 seconds
- Handle pagination better (implement pagination for market page)

Another issue is that many of the queries are polling globally, meaning data is being asked for when it is not required in that specific screen. Currently not as straightforward as moving as our notification system needs to know when data updated globally (e.g player bids on an item, the loader/noti needs to know when the market data has changed to let the user know). This can be improved with more specific queries

**Comment by loothero** [comment]
To help soften the impact of this issue, we're going to upgrade our aws server from a t3.large to a c6a.xlarge.

I expect this to yield a 10-20x increase in compute power. Compensating for software inefficiencies with hardware is of course not sustainable but this is very high +EV for an extra $40/month.

**Comment by starknetdev** [comment]
This should have been improved largely by #126. Will continue to monitor
